# Generated by Django 3.1 on 2020-08-20 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast_or_roast', models.BooleanField(default=True)),
                ('body', models.CharField(max_length=280)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
